depend: [ProtocolLib]
name: OnlyMostlyDead
main: hydrogenn.omd.OnlyMostlyDead
version: 1.2
commands:
  omd:
    description: Interact with a player corpse.
    usage: "/omd <subcommand> <playername> OR /omd help"