name: Notes
main: hydrogenn.notes.Notes
version: 1.4
softdepend: [Firebalance]
commands:
  note:
    description: Modifies a note.
    usage: "/note help"
  stamp:
    description: Copies a held stamp to a held paper.
    usage: /stamp