name: QuotableRules
main: hydrogenn.quotableRules.QuotableRules
version: 1.0
commands:
  newrule:
    description: Adds a rule.
    usage: /rule <remove/change/add/reload> ...
  rules:
    description: Shows the rules.
    usage: /rules
  quote:
    description: Quote a rule.
    usage: /quote <rule>